# =============================================================================
# setup.ps1  -  One-shot RDS sandbox setup
# Run from: infra/terraform/
# Usage:    .\setup.ps1
#           .\setup.ps1 -DbPassword "AnotherPass99!"
# =============================================================================

param(
    [string]$DbPassword   = "MyPassword123!",
    [string]$DbUser       = "appuser",
    [string]$DbName       = "appdb",
    [string]$KeyPairName  = "my-sandbox-key",
    [string]$Region       = "us-east-1",
    [string]$SsmPath      = "/ci-cd-project/backend",
    [string]$ProjectName  = "ci-cd-project",
    [string]$Environment  = "dev"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Step([string]$msg) {
    Write-Host ""
    Write-Host "==> $msg" -ForegroundColor Cyan
}
function Write-Ok([string]$msg) {
    Write-Host "    [OK] $msg" -ForegroundColor Green
}
function Write-Warn([string]$msg) {
    Write-Host "    [WARN] $msg" -ForegroundColor Yellow
}

# Step 1: Verify tools
Write-Step "Checking prerequisites"
try { aws --version | Out-Null } catch { throw "AWS CLI not found." }
try { terraform version | Out-Null } catch { throw "Terraform not found." }
Write-Ok "AWS CLI and Terraform are available"

# Step 2: Get current public IP
Write-Step "Detecting your public IP"
$MyIp = (Invoke-RestMethod -Uri "https://checkip.amazonaws.com").Trim()
$SshCidr = "$MyIp/32"
Write-Ok "Your IP: $SshCidr"
# Step 2b: Import existing key pair into this sandbox
Write-Step "Importing key pair into sandbox"
$keyExists = aws ec2 describe-key-pairs --key-names $KeyPairName --region $Region 2>$null
if (-not $keyExists) {
    Write-Warn "Key pair '$KeyPairName' not in this sandbox - importing from .pem file"
    
    # Extract public key from the existing .pem
    $pubKey = ssh-keygen -y -f "$KeyPairName.pem"
    $pubKeyBase64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($pubKey))
    
    aws ec2 import-key-pair `
        --key-name $KeyPairName `
        --public-key-material $pubKeyBase64 `
        --region $Region | Out-Null
    
    Write-Ok "Key pair '$KeyPairName' imported successfully"
} else {
    Write-Ok "Key pair '$KeyPairName' already exists in this sandbox"
}
# Step 3: Create SSM parameters FIRST (before any terraform command)
Write-Step "Creating SSM parameters"

aws ssm put-parameter --name "$SsmPath/DB_HOST"     --value "placeholder" --type SecureString --overwrite --region $Region | Out-Null
Write-Ok "Set $SsmPath/DB_HOST = placeholder"

aws ssm put-parameter --name "$SsmPath/DB_USER"     --value $DbUser       --type SecureString --overwrite --region $Region | Out-Null
Write-Ok "Set $SsmPath/DB_USER = $DbUser"

aws ssm put-parameter --name "$SsmPath/DB_PASSWORD" --value $DbPassword   --type SecureString --overwrite --region $Region | Out-Null
Write-Ok "Set $SsmPath/DB_PASSWORD = (hidden)"

aws ssm put-parameter --name "$SsmPath/DB_NAME"     --value $DbName       --type SecureString --overwrite --region $Region | Out-Null
Write-Ok "Set $SsmPath/DB_NAME = $DbName"

# Step 4: Write terraform.tfvars
Write-Step "Writing terraform.tfvars"

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"
$tfvarsContent = "# Auto-generated by setup.ps1 - $timestamp`n"
$tfvarsContent += "key_pair_name = `"$KeyPairName`"`n"
$tfvarsContent += "ssh_cidr      = `"$SshCidr`"`n"
$tfvarsContent += "`n"
$tfvarsContent += "use_json_storage   = false`n"
$tfvarsContent += "use_ssm_parameters = true`n"
$tfvarsContent += "`n"
$tfvarsContent += "db_skip_final_snapshot = true`n"
$tfvarsContent += "db_deletion_protection = false`n"
$tfvarsContent += "`n"
$tfvarsContent += "frontend_build_output_path = `"dist/client/browser`"`n"
$tfvarsContent += "`n"
$tfvarsContent += "aws_region   = `"$Region`"`n"
$tfvarsContent += "project_name = `"$ProjectName`"`n"
$tfvarsContent += "environment  = `"$Environment`"`n"

[System.IO.File]::WriteAllText("$PWD\terraform.tfvars", $tfvarsContent, [System.Text.Encoding]::ASCII)
Write-Ok "terraform.tfvars written"

# Step 5: terraform init
Write-Step "Running terraform init"
terraform init -upgrade
Write-Ok "Init complete"

# Step 6: Destroy existing state if any
Write-Step "Checking for existing resources"
$existing = terraform state list 2>$null
if ($existing) {
    Write-Warn "Existing resources found - destroying first"
    terraform destroy -auto-approve
    Write-Ok "Destroy complete"
} else {
    Write-Ok "No existing state - skipping destroy"
}

# Step 7: Apply
Write-Step "Running terraform apply (takes ~10-15 min for RDS + EC2 build)"
terraform apply -auto-approve

# Step 8: Print outputs
Write-Step "Deployment complete"
$BackendDns  = terraform output -raw backend_public_dns
$FrontendDns = terraform output -raw frontend_public_dns
$RdsEndpoint = terraform output -raw rds_endpoint

Write-Host ""
Write-Host "  Backend  : http://$BackendDns"  -ForegroundColor White
Write-Host "  Frontend : http://$FrontendDns" -ForegroundColor White
Write-Host "  RDS      : $RdsEndpoint"        -ForegroundColor White
Write-Host ""
Write-Host "  SSH backend  : ssh -i $KeyPairName.pem ec2-user@$BackendDns"  -ForegroundColor DarkCyan
Write-Host "  SSH frontend : ssh -i $KeyPairName.pem ec2-user@$FrontendDns" -ForegroundColor DarkCyan
Write-Host ""

# Step 9: Health check with retry
Write-Step "Waiting for backend to be healthy (up to 3 min)"
$HealthUrl   = "http://$BackendDns/health"
$MaxAttempts = 18
$Delay       = 10

for ($i = 1; $i -le $MaxAttempts; $i++) {
    try {
        $res = Invoke-RestMethod -Uri $HealthUrl -TimeoutSec 5
        Write-Ok "Backend healthy!"
        Write-Host ""
        Write-Host "  Test API : curl http://$BackendDns/api/users" -ForegroundColor DarkCyan
        break
    } catch {
        Write-Warn "Attempt $i/$MaxAttempts - not ready yet, retrying in ${Delay}s..."
        Start-Sleep -Seconds $Delay
    }
    if ($i -eq $MaxAttempts) {
        Write-Warn "Health check timed out. App may still be starting."
        Write-Warn "Try manually: curl $HealthUrl"
    }
}

Write-Host ""
Write-Host "Done! DB_HOST was set automatically by Terraform - no manual SSH needed." -ForegroundColor Green