# Auto-generated by setup.ps1 - 2026-05-07 09:33
key_pair_name = "my-sandbox-key"
ssh_cidr      = "41.229.70.2/32"

use_json_storage   = false
use_ssm_parameters = true

db_skip_final_snapshot = true
db_deletion_protection = false

frontend_build_output_path = "dist/client/browser"

aws_region   = "us-east-1"
project_name = "ci-cd-project"
environment  = "dev"
